name: Build project and release
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release VueTorrent
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm ci

      - name: Build VueTorrent
        run: npm run build

      - name: Zip Artifact
        run: |
          zip -r vuetorrent.zip vuetorrent/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: vuetorrent.zip
          generate_release_notes: true
